apiVersion: v1
kind: Secret
metadata:
  name: dondns-rs-secret
type: Opaque
stringData:
  DONDNS_USERNAME: "your-username"
  DONDNS_PASSWORD: "your-dondns-key"
  DONDNS_HOSTNAME: "home.example.com"
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: dondns-rs
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 16
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: dondns
              image: ghcr.io/diegojfer/dondns-rs:latest
              envFrom:
                - secretRef:
                    name: dondns-rs-secret
